FROM alpine:3.23.0

RUN apk add --no-cache \
        docker-cli \
        curl \
        git

RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.68.2

RUN mkdir -p /etc/trivy/templates

COPY trivy/templates/html.tpl /etc/trivy/templates/html.tpl

RUN addgroup -S debug && adduser -S debug -G debug

RUN chown debug:debug /etc/trivy/templates/html.tpl

USER debug

CMD [ "sleep", "9999999999" ]